name: Publish
on: 
  push: 
    branches: 
      - master
jobs:
  pre-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print Hello World
        run: |
          echo "Hello World"
  publish: 
    runs-on: ubuntu-latest
    needs: pre-publish
    steps:
      - name: Checkout repository
        run: |
          echo "Publishing"
