name: Test docker action
on: 
  push: 
    branches: 
      - master
jobs:
  test-default-message:
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.hello.outputs.output }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print Hello World
        id: hello
        uses: ./test-docker-action

  test-user-message:
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.hello.outputs.output }}
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Print Hello Tulip Tree Tech
        id: hello
        uses: ./test-docker-action
        with:
          who-to-greet: 'Tulip Tree Tech'

  checks-outputs:
    runs-on: ubuntu-latest
    needs: [test-default-message, test-user-message]
    steps:
      - name: Check first output
        run: |
          [[ "${{ needs.test-default-message.outputs.output }}" == "Hello World" ]]
      
      - name: Check first output
        run: |
          [[ "${{ needs.test-user-message.outputs.output }}" == "Hello Tulip Tree Tech" ]]
        